### ISSUE TITLE
Format Date

### ISSUE THREAD

**Issue by andersoal** [ayarabis/json2raml#1]
RAML has specific [types for Date](https://github.com/jonathanfiss/convert-json-to-raml-datatype/blob/master/lib/service/convertJsonToRamlDataType.js). The extension miss this:

Example of JSON:

```json
{
  "birthday": "2015-05-23",
  "lunchtime": "12:30:00",
  "fireworks": "2015-07-04T21:00:00",
  "created": "2016-02-28T16:41:41.090Z",
  "If-Modified-Since": "Sun, 28 Feb 2016 16:41:41 GMT"
}
```

The RAML DataType get thought the extension:

```yaml
#%RAML 1.0 DataType

type: object
properties:
  birthday:
    type: string
  lunchtime:
    type: string
  fireworks:
    type: string
  created:
    type: string
  If-Modified-Since:
    type: string

example: {
  "birthday": "2015-05-23",
  "lunchtime": "12:30:00",
  "fireworks": "2015-07-04T21:00:00",
  "created": "2016-02-28T16:41:41.090Z",
  "If-Modified-Since": "Sun, 28 Feb 2016 16:41:41 GMT"
}
```

It could be:

```yaml
#%RAML 1.0 DataType

type: object
properties:
  birthday:
    type: date-only
  lunchtime:
    type: time-only
  fireworks:
    type: datetime-only
  created:
    type: datetime
  If-Modified-Since:
    type: datetime
    format: rfc2616

example: {
  "birthday": "2015-05-23",
  "lunchtime": "12:30:00",
  "fireworks": "2015-07-04T21:00:00",
  "created": "2016-02-28T16:41:41.090Z",
  "If-Modified-Since": "Sun, 28 Feb 2016 16:41:41 GMT"
}
```
